### ISSUE TITLE
Filebeat 7.12

### ISSUE THREAD

**Issue by ThomSwiss** [barqshasbite/filebeat-scrubber#1]
Hello
With filebeat 7.12 it get this issue. Do I something wrong or is it not compatible to the newest filebeat version?

(scruberws) root@wilux2:~/scruberws# filebeat_scrubber --move --registry-file "/var/lib/filebeat/registry/filebeat/log.json" --destination "/tmp" --verbose
[2021-03-28 10:02:54,811][INFO] Filebeat Scrubber running with arguments:
[2021-03-28 10:02:54,811][INFO]   age = 0
[2021-03-28 10:02:54,811][INFO]   delete = False
[2021-03-28 10:02:54,811][INFO]   filter_regex = None
[2021-03-28 10:02:54,811][INFO]   interval = 0
[2021-03-28 10:02:54,811][INFO]   move = True
[2021-03-28 10:02:54,811][INFO]   registry_file = /var/lib/filebeat/registry/filebeat/log.json
[2021-03-28 10:02:54,811][INFO]   show_summary = False
[2021-03-28 10:02:54,811][INFO]   target_directory = /tmp
[2021-03-28 10:02:54,811][INFO]   type = None
[2021-03-28 10:02:54,812][INFO]   verbose = True
Traceback (most recent call last):
  File "/root/scruberws/bin/filebeat_scrubber", line 8, in <module>
    sys.exit(main())
  File "/root/scruberws/lib/python3.8/site-packages/filebeat_scrubber/filebeat_scrubber.py", line 331, in main
    scrub(args, stats)
  File "/root/scruberws/lib/python3.8/site-packages/filebeat_scrubber/filebeat_scrubber.py", line 303, in scrub
    registry_data = _read_registry_file(args)
  File "/root/scruberws/lib/python3.8/site-packages/filebeat_scrubber/filebeat_scrubber.py", line 186, in _read_registry_file
    data = json.load(_registry_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 20)

**Comment by MiroslavShinikov** [comment]
The log.json you mentioned is with a different format than the previous registry file, so it does not work. Still you can use the current active registry snapshot file which has the correct format and the script still works. 

For example: /var/lib/filebeat/registry/filebeat/556409.json . 

It changes so you can find out which is the current now by checking :

cat /var/lib/filebeat/registry/filebeat/active.dat
/var/lib/filebeat/registry/filebeat/556409.json
